trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    containerRegistry: 'testacr' #Name of the service principal created for your Azure Container Registry in ADO
    repository: 'nodejs' #repository Name in the ACR, If it doesn't exist the pipeline will create it
    dockerfile: '**/Dockerfile' # This searches Dockeefile in Repo, We can specifiy exact location as well
    tags: | # Two versions will be pushed one to the latest and one with build id
      $(Build.BuildId)
      latest